services:
  api:
    build:
      context: ./TenantRating.API
      dockerfile: Dockerfile
    container_name: tenant-rating-api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./certs:/usr/local/share/ca-certificates/custom:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AzureDocumentIntelligence__ApiKey=${AZURE_API_KEY}
      - AzureDocumentIntelligence__Endpoint=${AZURE_ENDPOINT}
      - AzureDocumentIntelligence__ModelId=${AZURE_MODEL_ID}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Resend__ApiKey=${RESEND_API_KEY}
      - Resend__FromEmail=no-reply@kaliscore.tech
      - Resend__UseSandboxRecipient=false
      - SmsSettings__Key=${SMS_KEY}
      - SmsSettings__User=${SMS_USER}
      - SmsSettings__Pass=${SMS_PASS}
    restart: always

  client:
    build:
      context: ./TenantRating.Client
      dockerfile: Dockerfile
    container_name: tenant-rating-client
    ports:
      - "800:80"
    depends_on:
      - api
    restart: always
