name: Deploy to AWS

on:
  push:
    branches:
      - main
      - azriel/features

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then echo "KEY IS EMPTY"; else echo "KEY IS SET"; fi
          if [ -z "${{ secrets.SSH_HOST }}" ]; then echo "HOST IS EMPTY"; else echo "HOST IS SET"; fi

      - name: Deploy to AWS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd tanentProjv2
            git pull origin ${{ github.ref_name }}
            sudo docker compose up --build -d
            sudo docker system prune -f
